const state = {
  FeName:'',
  isShow: false,
  deleteRoleIsShow: false,
  deletePayIsShow: false,
  deleteSupplierIsShow: false,
  deleteRoomIsShow: false,
  deleteEmpManagerIsShow: false,
  deleteEmpPromotionIsShow: false,
  deleteEmpTrainIsShow: false,
  deleteEmpChangeIsShow: false,
  deleteProIndexIsShow: false,
  deleteCard: false,
  queryMapIsShow: false,
  currentRow: {},
  patchCard: false,
  deleteMemberCard: false,
  MeGuid: '',
  addMemberIsShow: false,
  addStorageIsShow: false,
  deleteStorageIsShow: false,
  addCommuniceIsShow: false,
  deleteCommuniceIsShow: false,
  editCommuniceIsShow: false,
  addDelayIsShow: false,
  addTransferCardIsShow: false,
  SelectCardIsShow: false,
  PayMethodIsShow: false,
  CardSaleStaffIsShow: false,
  GiveProjectIsShow: false,
};
export default state;
